logging:
  level: INFO
  loggers:
    com.oracle: DEBUG

database:
    driverClass: com.mysql.cj.jdbc.Driver
    user: root
    password: Welc0me_2017
    url: jdbc:mysql://140.86.34.69:3306/EmployeeMySQLDB?autoReconnect=true&useSSL=false
